# Configuração do Netlify

# Configurações de build
[build]
  command = "npm run build"
  publish = "hcb-gestao-files/build"

# Redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
